config = {'train_data_path':['H:/Luna16_Data/Extracted/luna/subset0/',
                             'H:/Luna16_Data/Extracted/luna/subset1/',
                             'H:/Luna16_Data/Extracted/luna/subset2/',
                             'H:/Luna16_Data/Extracted/luna/subset3/',
                             'H:/Luna16_Data/Extracted/luna/subset4/',
                             'H:/Luna16_Data/Extracted/luna/subset5/',
                             'H:/Luna16_Data/Extracted/luna/subset6/',
                             'H:/Luna16_Data/Extracted/luna/subset7/',
                             'H:/Luna16_Data/Extracted/luna/subset8/'],
          'val_data_path':['H:/Luna16_Data/Extracted/luna/subset9/'],
          'test_data_path':['H:/Luna16_Data/Extracted/luna/subset9/'], 
          
          'train_preprocess_result_path':'H:/Luna16_Data/DeepLung/preprocess/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'H:/Luna16_Data/DeepLung/preprocess/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'H:/Luna16_Data/DeepLung/preprocess/',
          
          'train_annos_path':'H:/Luna16_Data/DeepLung/CSVFILES/annotations.csv',
          'val_annos_path':'H:/Luna16_Data/DeepLung/CSVFILES/annotations.csv',
          'test_annos_path':'H:/Luna16_Data/DeepLung/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'H:/Luna16_Data/Extracted/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'H:/Luna16_Data/DeepLung/preprocess/',
          'luna_data':'H:/Luna16_Data/Extracted/luna/',
          'luna_label':'H:/Luna16_Data/DeepLung/CSVFILES/annotations.csv'
         } 
